on:
  workflow_run:
    workflows: ["Test"]
    types:
      - requested

concurrency:
  group: ${{ github.ref == 'refs/heads/master' && format('ci-default-branch-{0}-{1}', github.sha, github.workflow) || format('ci-pr-{0}-{1}', github.ref, github.workflow) }}
  cancel-in-progress: true

jobs:
  e2e:
    name: e2e
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Get Yarn cache directory path
        id: yarn-cache-dir-path
        run: echo "::set-output name=dir::$(yarn config get cacheFolder)"
      - name: Setup Yarn cache
        uses: actions/cache@v3
        id: yarn-cache
        with:
          path: ${{ steps.yarn-cache-dir-path.outputs.dir }}
          key: ${{ runner.os }}-yarn-${{ hashFiles('**/yarn.lock') }}
          restore-keys: ${{ runner.os }}-yarn-
      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: 16
      - name: DUMMY
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          GITLAB_OAUTH_APPLICATION_CLIENT_ID: ${{ secrets.GITLAB_OAUTH_APPLICATION_CLIENT_ID }}
          GITLAB_OAUTH_APPLICATION_SECRET: ${{ secrets.GITLAB_OAUTH_APPLICATION_SECRET }}
          GITLAB_PAT: ${{ secrets.GITLAB_PAT }}
        run: echo $GITHUB_TOKEN && node ./scripts/print.js
